### PR TITLE
Various Improvements / Fixes

### LINKED ISSUE #1: Add usgov environment to Connect-AzureAD
Just looking quickly on the mobile site and it looks like there isn't an option for setting the 'Connect-AzureAD -AzureEnvironmentName AzureUSGovernment' option. Otherwise looks great and will check it out!

### LINKED ISSUE #3: Switch to ExchangeOnlineManagement
Please switch to using the ExchangeOnlineManagement module instead of CloudConnect for connecting to Exchange Online.

The ExchangeOnlineManagement module is the officially supported way to connect to Exchange Online.  The actual implemention is just a few small code updates

### LINKED ISSUE #4: File gives error for line 156
# 🐛 Bug Report

Line |
 156 |  … etails px-3 px-md-4 px-lg-5 flex-wrap flex-md-nowrap" role="banner" >
     |                                                                         ~
     | Missing file specification after redirection operator.

## To Reproduce

Run the Sparraw.ps1 file

## Expected behavior

File was supposed to run

## Any helpful log output

Line |
 156 |  … etails px-3 px-md-4 px-lg-5 flex-wrap flex-md-nowrap" role="banner" >
     |                                                                         ~
     | Missing file specification after redirection operator.

### LINKED ISSUE #7: Error output from PS1 execution
Hi,

We are attempting to run 'C:\temp\Sparrow.ps1', however we continue to receive the following error:

image

### LINKED ISSUE #12: $ExportDir not used for export
Not sure if it's been mentioned yet. I haven't run the script yet as I'm waiting on the permissions to be provisioned, but looking over the script I noticed the $ExportDir variable that can be changed to wherever the user prefers their exports/output to go, but it seems if a user were to want to change this, it wouldn't have any effect:

Line 22:
    $ExportDir = "$home\Desktop\ExportDir"
    If (!(Test-Path $ExportDir)){
        New-Item -Path $ExportDir -ItemType "Directory" -Force
    }

Line 358
        If ($AppendType -eq "Append"){
            $DataArr | Export-csv $home\Desktop\ExportDir\$CsvName.csv -NoTypeInformation -Append
        } Else {
            $DataArr | Export-csv $home\Desktop\ExportDir\$CsvName.csv -NoTypeInformation
        }

I'd imagine you would want this to be something more like:

        If ($AppendType -eq "Append"){
            $DataArr | Export-csv $ExportDir\$CsvName.csv -NoTypeInformation -Append
        } Else {
            $DataArr | Export-csv $ExportDir\$CsvName.csv -NoTypeInformation
        }

### LINKED ISSUE #14: Change parameter value
# 🚀 Feature Proposal

In Export-UALData function, change "Sharepoint" value of -WorkloadType parameter to "SharePoint"
* function call/parameter passing on line 143
* use of parameter value on line 324 

## Motivation

"Sharepoint" is an incorrect capitalization of the service. A PR was raised to fix this in the comments (#13), but the repo owners should make sure any parameter value changes have no additional effect.

## Example

Minor typographical change.

## Pitch

This is only to correctly identify the queried service in Microsoft M365.

### PR DESCRIPTION
**Pull request by NoMoreFood**
- Addressed problem where desktop may not be directly under home directory
- Added ability to choose specific environment
- Moved to new Exchange module to better support MFA
- Parameterized file to allow user to specify common variables
- Parameterized functions to reduce use of global variables
- Expanded default time range to one year
- Added warning when log data may be truncated
- Added code to merge output files into a single Excel file

### CODE REVIEW

**Comment by NoMoreFood** [comment]
- Addresses https://github.com/cisagov/Sparrow/issues/3
- Addresses https://github.com/cisagov/Sparrow/issues/1

**Comment by NoMoreFood** [comment]
Also updated README based on changes and to mitigate download issues as likely demonstrated in https://github.com/cisagov/Sparrow/issues/4 and https://github.com/cisagov/Sparrow/issues/7.

**Comment by ag-michael** [comment]
@NoMoreFood Can you please update the Readme as well, I was having errors, turns out it is due to not having 'ExchangeOnlineManagement' installed.

**Comment by NoMoreFood** [comment]
@ag-michael Already done as part of this pull request and is readable in my fork; please let me know if you think it's missing any else: https://github.com/NoMoreFood/Sparrow

**Comment by DeemOnSecurity** [comment]
Great work! We will be making some minor modifications before merging. We intentionally kept the CSV output as separate files, but will add a switch to optionally create one output file. Should have it put together at some point tomorrow.

**Comment by yellow-starburst** [comment]
@NoMoreFood I received the following error. I believe it may be related to powershell remoting. 
`New-ExoPSSession : Create Powershell Session is failed using OAuth`
`...WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.3\ExchangeOnlineManagement.psm1:426
char:30`

**Comment by DeemOnSecurity** [comment]
Belay my last message, we will add functionality in a later push on our part and will be merging this now. Thank you again for your contribution.

**Comment by DeemOnSecurity** [comment]
> @NoMoreFood I received the following error. I believe it may be related to powershell remoting.
> `New-ExoPSSession : Create Powershell Session is failed using OAuth`
> `...WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.3\ExchangeOnlineManagement.psm1:426 char:30`

@yellow-starburst  [This](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_o365admin-mso_dep365-mso_o365b/exchange-online-connection-issues/7c535f8d-da5b-4116-93e1-f17ccc533b80) forum discussion may help, please raise an issue if the problem continues after troubleshooting.

**Pull request merged**
